# Generated by Django 5.2.7 on 2025-11-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="Untitled", max_length=200),
        ),
    ]
