# Generated by Django 5.2.7 on 2025-11-14 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_post_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="body",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="parent",
        ),
    ]
