# Generated by Django 5.2.7 on 2025-11-14 18:48

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_rename_body_comment_content_remove_comment_parent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="Announcement",
        ),
        migrations.DeleteModel(
            name="Badge",
        ),
        migrations.DeleteModel(
            name="Community",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="content",
            new_name="body",
        ),
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="font_scale",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="theme",
        ),
        migrations.AddField(
            model_name="post",
            name="upvotes",
            field=models.ManyToManyField(
                blank=True, related_name="upvoted_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="guest_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name="Event",
        ),
    ]
